#!/usr/bin/env bash

greet() {
    local name=$1 #variavel name eh o primeiro argumento passado para essa func
    echo "hello $name" #imprime a variavel $name
}

for name in "$@"; do #representa um vetor de parametros no imput, aceita varias strings separadas por " "
    greet "$name" #executa func greet
done

