#!/usr/bin/env bash

a=2 # atribui 2 a variavel a
b=2 # atribui 2 a variavel b
if [[ $a == $b ]]; then # condicional para executar bloco se valor de a for igual ao valor de b
    echo 'a and b are the same' # imprime a mensagem que a e b sao iguais
fi # fim do bloco

c=2 # atribui 2 a variavel c
d=3 # atribui 3 a variavel d
if [[ $c != $d ]]; then # condicional para executar bloco se valor de c for diferente do valor de d
    echo 'c and d are NOT the same' # imprime a mensagem que nao sao iguais
fi # fim do bloco

if [[ -f file.txt ]]; then # testa se o arquivo file.txt existe: "True if file exists and is a regular file." fonte: "help test" no terminal bash para documentacao
    echo 'file.txt exists and is a file' # imprime a mensageem dizendo que existe
    while [[ -f file.txt ]]; do # loop while para continuar impriminto uma msg enquanto o arquivo existir
        echo 'file.txt found' # msg do loop
        sleep 1 # intervalo de 1 seg para nao ficar spammando
    done # fim do loop
    echo 'file.txt deleted' # avisa quando a file for deletada
else # nao encontrar a file, o script avisa q n achou
    echo 'file.txt not found' # msg se n encontrar a file
fi # fim do bloco