#!/usr/bin/env bash

s=$1 # define a variavel de input para ser o primeiro parametro apos o comando

case "$s" in # estrutura case parecida com switch em C
    vini) # se $1 for vini
        echo "oi vini"
        ;; # fim do bloco, semelhante a break
    vn3)
        echo "oi vn3"
        ;;
    bomboclat)
        echo "DA BOMBOCLAT"
        ;;
    *) # usado para default "*" = qualquer outra coisa WILDCARDS
        echo "identifique-se ou morra"
        ;;
esac # fim do switch

# case "$s" in
#    vini) echo "oi vini"
#    vn3) echo "oi vn3"
#    bomboclat) echo "DA BOMBOCLAT"
#    *) echo "identifique-se ou morra"
# esac

# se for so 1 comando pode colocar na mesma linha